Добавлена реализация ТЗ номер 6
dedulyxx/java-kanban pull request #1
Opened 2024-06-28 19:53 UTC by dedulyxx

2024-06-28 21:01 UTC, dedulyxx commented
CheckStyle - Error:  /home/runner/work/java-kanban/java-kanban/./src/ru/practicum/java/tasks/Subtask.java:17:37: Parameter name 'Status' must match pattern '^[a-z]([a-zA-Z0-9]*)?$'. [ParameterName]

Я как только не переименовывал Status в enum, но он все равно ругается, хотя по общепринятому стилю же должны быть заглавные буквы, разве нет? Подскажи что не так(

2024-06-30 10:30 UTC, Fleaman777 requested changes

2024-06-30 10:30 UTC, Fleaman777 commented on src/Main.java
> +        System.out.println("------------------------------------------------------------");
"------------------------------------------------------------" - можно вынести в константу, что бы не повторять это значение 
или вообще использовать метод repeat у String

2024-06-30 10:30 UTC, Fleaman777 commented on src/ru/practicum/java/manager/Node.java
> +public class Node<Task> {
этот класс можно сделать внутри менеджера истории, так как он непосредственно с ним связан

2024-06-30 10:30 UTC, Fleaman777 commented on src/ru/practicum/java/manager/InMemoryHistoryManager.java
> +    class LinkedListNew<Task> {
можно не создавать этот класс, так как вся эта логика с прилинковыванием задачи и пр. есть логика InMemoryHistoryManager класса, 
те все его методы сразу определить в InMemoryHistoryManager и использовать их напрямую

2024-06-30 10:30 UTC, Fleaman777 commented on src/ru/practicum/java/manager/InMemoryHistoryManager.java
> +            for (int i = 0; i < size; i++) {
как еще один вариант, пройтись в цикле while

2024-06-30 10:30 UTC, Fleaman777 commented on src/ru/practicum/java/test/ru/practicum/java/tasks/TaskTest.java
> +    void CheckStatusWhenSetStatusDONE() {
название метода по джава код стайлу должно быть с маленькой буквы

2024-06-30 10:30 UTC, Fleaman777 commented on src/ru/practicum/java/test/ru/practicum/java/manager/InMemoryTaskManagerTest.java
> +    }
еще бы тест добавить по ТЗ

"...
С помощью сеттеров экземпляры задач позволяют изменить любое своё поле, но это может повлиять на данные внутри менеджера. Протестируйте эти кейсы и подумайте над возможными вариантами решения проблемы."

2024-06-30 10:34 UTC, Fleaman777 commented
что касается падающего билда, 
Скорее всего из-за метода в классе Subtask

   @Override
    public Subtask setStatus(Status Status) {
        super.setStatus(Status);
        return this;
    }
    
    название аргумента метода должно быть с маленькой буквы 
    Status status

2024-06-30 15:33 UTC, dedulyxx commented on src/ru/practicum/java/test/ru/practicum/java/manager/InMemoryTaskManagerTest.java
> +    }
Я добавил тест что можно изменить напрямую статус, логично делать эти поля приватными, но как дать возможность в классе менеджера их менять. Прочитав про рефлексию, нашел способ, попытался реализовать, но тогда нужно у класса Task и всех его наследников делать поле приватным и менять логику у менеджера. Надо ли это сейчас было делать или нужен был просто тест. Или там вообще не рефлексия, а другой способ?

2024-07-01 19:05 UTC, Fleaman777 approved these changes

2024-07-01 19:05 UTC, Fleaman777 commented on src/ru/practicum/java/test/ru/practicum/java/manager/InMemoryTaskManagerTest.java
> +    }
по хорошему, поле status в классе Task должно быть protected, но это все равно не решает вопрос) 

через рефлексию - это прям оверхэд, тонкая вещь, которой нужно пользоваться аккуратно, со знанием, тк она по сути нарушает весь ооп со своим подходом и принципами, ну и как результат не очень безопасная. Поэтому ее использовать сейчас не надо, 

в тесте просто нужно проверить, что сеттер методы работают, но устанавливают новое значение в объекте, но как там и сказано, это может повлиять на состояние задач внутри менеджера, например у объекта можно будет установить новый айдишник, который не будет соответствовать используемому в мапе или статус эпика установится через сеттер, хотя по факту он должен только рассчитываться,
вот как раз над решением этих проблем предлагают подумать) (но реализовывать не обязательно)

2024-07-01 19:54 UTC, merged